# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0212499d2baa30773dc505246546db8f898c18e8f94baba104ba107697a19125249940f190182854316d1f494ad9eeca3f3dc3f0d81c47a34e9f3bdb2e53b136

test:
  secret_key_base: 962ef7965e84b7ec7b62adda7e2aaae2faaa174c630b91ac43dbbedaf760818220afd0c56235682b23aacddbe71bbb5952d7403e0a05721f6f223dbb19e3fa4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
